apiVersion: security-profiles-operator.x-k8s.io/v1beta1
kind: SeccompProfile
metadata:
  name: notify-dangerous
  annotations:
    description: "Allow most syscalls except dangerous ones where it uses notify."
spec:
  defaultAction: SCMP_ACT_ALLOW
  architectures:
  - SCMP_ARCH_X86_64
  listenerPath: "/run/seccomp-agent.socket"
  #listenerMetadata: "DEFAULT_ACTION=kill-container"
  #listenerMetadata: "DEFAULT_ACTION=freeze-container\nMIDDLEWARE=falco"
  listenerMetadata: "DEFAULT_ACTION=kill-container\nMIDDLEWARE=falco"

  syscalls:

  - action: SCMP_ACT_NOTIFY
    names:
    - acct
    - add_key
    - bpf
    - clock_adjtime
    - clock_settime
    - create_module
    - delete_module
    - finit_module
    - get_kernel_syms
    - get_mempolicy
    - init_module
    - ioperm
    - iopl
    - kcmp
    - kexec_file_load
    - kexec_load
    - keyctl
    - lookup_dcookie
    - mbind
    - mount
    - move_pages
    - name_to_handle_at
    - nfsservctl
    - open_by_handle_at
    - perf_event_open
    - personality
    - pivot_root
    - process_vm_readv
    - process_vm_writev
    - ptrace
    - query_module
    - quotactl
    - reboot
    - request_key
    - set_mempolicy
    - setns
    - settimeofday
    - stime
    - swapoff
    - swapon
    - _sysctl
    - sysfs
    - umount2
    - umount
    - unshare
    - uselib
    - userfaultfd
    - ustat
    - vm86old
    - vm86

